### ISSUE TITLE
Can't find the list of helpful slurm commands

### ISSUE THREAD

**Issue by carolinarr** [PrincetonUniversity/hpc_beginning_workshop#2]
Should we add the following table somewhere (or did I miss it? I expected it to be in the 07_slurm section):

Command | Description
sbatch <slurm_script> | Submit a job (e.g., sbatch calc.cmd)
squeue | Show   jobs in the queue
squeue -u   <username> | Show   jobs in the queue for a specific user (e.g., squeue -u ceisgruber)
squeue   --start | Report   the expected start time for pending jobs
squeue -j   <jobid> | Show   the nodes allocated to a running job
scancel   <jobid> | Cancel   a job (e.g., scancel 2534640)
scontrol   show jobid <jobid> | See   detailed info about a job
snodes | Show   properties of the nodes on a cluster (e.g., maximum memory)
sinfo | Show   how nodes are being used
sshare/sprio | Show   the priority assigned to jobs
smap/sview | Graphical   display of the queues
slurmtop | Text-based   view of cluster nodes
scontrol   show config | View   default parameter settings
sacct   --format="CPUTime,MaxRSS" | View   details about finished jobs. Use sacct -e to view list of everything you can   list in format.

**Comment by jdh4** [comment]
These commands have been added to the Slurm page.
